---
title: "Temple COVID-19 Spring 2021 Case Tracker"
author: "Amelia Winger and Colin Evans"
date: "6/29/2021"
output: html_document
---
# Call libraries
```{r, include = FALSE}
library(tidyverse)
library(httr)
library(rvest)
library(jsonlite)
library(scales)
library(zoo)
library(openair)
```
# Set up workspace
```{r, error = TRUE}
# Define the URL to POST to
posturl <- 'https://wabi-us-east2-api.analysis.windows.net/public/reports/querydata?synchronous=true'
```
# Create a loop that scrapes all the daily active cases
```{r, error = TRUE}
# Create an empty data frame
results <- data.frame()

# Create an array of dates between the current date and Jan. 1, 2021
## This will define the number of times the k loop will run
dates <- seq(as.Date("2021-01-01"), Sys.Date(), by=1)

# Create a variable to record how many times the k loop runs
p <- 0 

# Create a .json file that contains the POST body for every data point for every date
for (k in 1:length(dates)) { 
  
  # Add one to the loop counter
  p <- p + 1
  
  # Read the request payload into a variable
  requestpayload_1 <- read_file("requestpayload_1.json")
  # Replace the date in the request payload with the date the loop is currently on
  requestpayload_1 <- str_replace(requestpayload_1, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  # Write the variable back into the file
  write(requestpayload_1, "requestpayload_1.json")
  
  # Repeat for all data points
  
    requestpayload_2 <- read_file("requestpayload_2.json")
  requestpayload_2 <- str_replace(requestpayload_2, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  write(requestpayload_2, "requestpayload_2.json")
  
    requestpayload_3 <- read_file("requestpayload_3.json")
  requestpayload_3 <- str_replace(requestpayload_3, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  write(requestpayload_3, "requestpayload_3.json")
  
    requestpayload_4 <- read_file("requestpayload_4.json")
  requestpayload_4 <- str_replace(requestpayload_4, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  write(requestpayload_4, "requestpayload_4.json")
  
    requestpayload_5 <- read_file("requestpayload_5.json")
  requestpayload_5 <- str_replace(requestpayload_5, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  write(requestpayload_5, "requestpayload_5.json")
  
    requestpayload_6 <- read_file("requestpayload_6.json")
  requestpayload_6 <- str_replace(requestpayload_6, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  write(requestpayload_6, "requestpayload_6.json")
  
      requestpayload_7 <- read_file("requestpayload_7.json")
  requestpayload_7 <- str_replace(requestpayload_7, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  write(requestpayload_7, "requestpayload_7.json")
  
      requestpayload_8 <- read_file("requestpayload_8.json")
  requestpayload_8 <- str_replace(requestpayload_8, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  write(requestpayload_8, "requestpayload_8.json")
  
      requestpayload_9 <- read_file("requestpayload_9.json")
  requestpayload_9 <- str_replace(requestpayload_9, "\\d{4}\\-\\d{2}\\-\\d{2}", as.character(dates[k]))
  write(requestpayload_9, "requestpayload_9.json")

# Feed the request payload to the POST body for each data point
for (i in 1:9) {

post <- POST(posturl, add_headers('X-PowerBI-ResourceKey' = '6790e246-5fe5-4cd7-8343-cc026c5ce9cd',
                                  'User-Agent' = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)     Chrome/79.0.3945.88 Safari/537.36',
                                  'Content-Type' = "application/json"),
              body = upload_file(paste("requestpayload_",i,".json", sep="")))

# Convert all successful POSTs to data frames
if (post$status_code == 200) {
postcontent <- fromJSON(content(post)) %>% data.frame() 

postcontent_flat <- flatten(postcontent)

# Extract the relevant data from the data frame
results[k, i] <- data.frame((((postcontent_flat[[7]][[1]])[[2]][[1]])[[1]][[1]][[2]]))

} else {
  
  # Fill in all other values with NA
  results[k, i] <- data.frame(NA)
  
}

# Print loop statement to console
print(paste("Loop iteration ",p,"_",i," completed", sep=""))

}}
```
# Clean daily results data frame
```{r}
results_clean <- results

# Define column names
names <- c("Active_Cases", "Temple_Positivity_Rate", "Estimated_Recovered_Cases", "Date", "Total_Tests", "Philadelphia_Positivity_Rate", "Cases_Students_University_Housing", "Cases_Students_NonUniversity_Housing", "Cases_Employees")

# Assign column names
names(results_clean) <- names

# Rearrange columns 
results_clean <- results_clean %>% 
  select(Date, Active_Cases, Total_Tests, Estimated_Recovered_Cases, Temple_Positivity_Rate, Philadelphia_Positivity_Rate, Cases_Students_University_Housing, Cases_Students_NonUniversity_Housing, Cases_Employees) %>% 
  # Create a new column that contains all student causes
  mutate(Cases_Students = Cases_Students_NonUniversity_Housing + Cases_Students_University_Housing)

# Change positivity rate values to percentages
results_clean$Temple_Positivity_Rate <- percent(as.numeric(results_clean$Temple_Positivity_Rate), accuracy = 0.01)
results_clean$Philadelphia_Positivity_Rate <- percent(as.numeric(results_clean$Philadelphia_Positivity_Rate), accuracy = 0.01)

# Clean date string
results_clean$Date <- str_remove(results_clean$Date, "Last Updated: ")

# Only include dates when tests were conducted
results_clean <- results_clean %>% 
  filter(Total_Tests != 0)

tt <- as.Date(results_clean$Date, "%m/%d/%Y")
w <- seq_along(tt) - findInterval(tt - 7, tt)

# Calculate 7 day rolling average
results_clean <- results_clean %>% 
  arrange(as.Date(Date, "%m/%d/%Y")) %>% 
  mutate(sevendayaverage = gsub("0$", "", round(rollapplyr(Active_Cases, w, mean, fill = NA, align = "right"), 1)))

# Write results_clean to .csv
write_csv(results_clean, "results_clean.csv")
```

# Scrape all the weekly data
```{r}
weeklypost <- POST(posturl, add_headers('X-PowerBI-ResourceKey' = '6790e246-5fe5-4cd7-8343-cc026c5ce9cd',
                                  'User-Agent' = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)     Chrome/79.0.3945.88 Safari/537.36',
                                  'Content-Type' = "application/json"),
              body = upload_file("weeklyrequestpayload.json"))

# Convert all successful POSTs to data frames
if (post$status_code == 200) {
weeklypostcontent <- fromJSON(content(weeklypost)) %>% data.frame() 

weeklypostcontent_flat <- flatten(weeklypostcontent)

# Extract the relevant data from the data frame
weeklyresults <- data.frame((((weeklypostcontent_flat[[8]][[1]])[[2]][[1]])[[1]][[1]][[2]]))

} else {
  
  # Fill in all other values with NA
  weeklyresults <- data.frame(NA) }
```
# Clean the weekly results dataframe
```{r}
weeklyresults_clean <- weeklyresults

weekdates <- rev(c("12/27/20", "1/3/21", "1/10/21", "1/17/21", "1/24/21", "1/31/21", "2/7/21", "2/14/21", "2/21/21", "2/28/21", "3/7/21", "3/14/21", "3/21/21", "3/28/21", "4/4/21", "4/11/21", "4/18/21", "4/25/21"))

names(weeklyresults_clean) <- weekdates

weeklyresults_clean <- t(weeklyresults_clean) %>% data.frame()

weeknames <- c("na", "Cases", "Tests", "Temple_Positivity", "Philadelphia_Positivity")

names(weeklyresults_clean) <- weeknames

weeklyresults_clean <- subset(weeklyresults_clean, select = -na)

# Change positivity rate values to percentages
weeklyresults_clean$Temple_Positivity <- percent(as.numeric(weeklyresults_clean$Temple_Positivity), accuracy = 0.01)
weeklyresults_clean$Philadelphia_Positivity <- percent(as.numeric(weeklyresults_clean$Philadelphia_Positivity), accuracy = 0.01)

weeklyresults_clean$Week <- row.names(weeklyresults_clean)

rownames(weeklyresults_clean) <- c()

weeklyresults_clean <- weeklyresults_clean %>% 
  select(Week, everything())

# Write weeklyresults_clean to .csv
write_csv(weeklyresults_clean, "weeklyresults_clean.csv")
```